exports.seed = function (knex, Promise) {
  return knex('users').del()
    .then(function () {
      return knex('users').insert([
        {
          first_name: "Dane",
          last_name: "Parke",
          email: "dane.parke@colorado.edu",
          password: "password",
          country: "Australia",
          admin: true,
          profile_image: "http://daneparke-portfolio.surge.sh/Professional_headshot.png",
          about_me: "I am a Colorado Native who is excited to travel, meet new people, and experience new cultures!",
          travel_status: true,
          checkin_status: false,
          whats_app_number: '19708193277',
        },
        {
          first_name: "Apple",
          last_name: "Mac",
          email: "apple@mac.com",
          password: "password",
          country: "America",
          admin: true,
          profile_image: "https://www.apple.com/ac/structured-data/images/knowledge_graph_logo.png?201606271147",
          about_me: "I am an Apple employee, who I hope will soon be reviewing my app",
          travel_status: true,
          checkin_status: false,
          whats_app_number: '18283329878',
        },
        {
          first_name: "Kate",
          last_name: "Shaefer",
          email: "kate@email.com",
          password: "password",
          country: "Spain",
          admin: false,
          profile_image: "https://randomuser.me/api/portraits/women/81.jpg",
          about_me: "Hi I am Kate",
          travel_status: true,
          checkin_status: true,
          whats_app_number: '19283748293',
        },
        {
          first_name: "Beef",
          last_name: "Mitch",
          email: "beef@email.com",
          password: "password",
          country: "Scotland",
          admin: false,
          profile_image: "https://randomuser.me/api/portraits/women/3.jpg",
          about_me: "Hi I am Beef",
          travel_status: true,
          checkin_status: true,
          whats_app_number: '18293237299',
        },
        {
          first_name: "Grant",
          last_name: "Fogle",
          email: "grant@email.com",
          password: "password",
          country: "Japan",
          admin: false,
          profile_image: "https://randomuser.me/api/portraits/men/0.jpg",
          about_me: "Hi I am Grant",
          travel_status: true,
          checkin_status: true,
          whats_app_number: '12238273299',
        },
        {
          first_name: "Phil",
          last_name: "Hengemuhle",
          email: "phil@email.com",
          password: "password",
          country: "Russia",
          admin: false,
          profile_image: "https://randomuser.me/api/portraits/men/48.jpg",
          about_me: "Hi I am Phil",
          travel_status: true,
          checkin_status: true,
          whats_app_number: '19902388383',
        },
        {
          first_name: "Daniel",
          last_name: "Phonelath",
          email: "daniel@email.com",
          password: "password",
          country: "Spain",
          admin: false,
          profile_image: "https://randomuser.me/api/portraits/men/66.jpg",
          about_me: "Hi I am Daniel",
          travel_status: true,
          checkin_status: true,
          whats_app_number: '17389280394',
        },
        {
          first_name: "James",
          last_name: "Shultz",
          email: "james@email.com",
          password: "password",
          country: "America",
          admin: false,
          profile_image: "https://randomuser.me/api/portraits/men/73.jpg",
          about_me: "Hi I am James",
          travel_status: false,
          checkin_status: false,
          whats_app_number: '18293238282',
        },
        {
          first_name: "Kylie",
          last_name: "Ryan",
          email: "kylie@email.com",
          password: "password",
          country: "Italy",
          admin: false,
          profile_image: "https://randomuser.me/api/portraits/women/12.jpg",
          about_me: "Hi I am Kylie",
          travel_status: true,
          checkin_status: true,
          whats_app_number: '17045266868',
        },
      ]);
    });
};